# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QGroupBox,
    QHBoxLayout, QLCDNumber, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(902, 626)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(0, 0))
        MainWindow.setAutoFillBackground(False)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_Test_as = QAction(MainWindow)
        self.actionSave_Test_as.setObjectName(u"actionSave_Test_as")
        self.actionPrint_Window = QAction(MainWindow)
        self.actionPrint_Window.setObjectName(u"actionPrint_Window")
        self.actionConnect = QAction(MainWindow)
        self.actionConnect.setObjectName(u"actionConnect")
        self.actionDisconnect = QAction(MainWindow)
        self.actionDisconnect.setObjectName(u"actionDisconnect")
        self.actionManage_Connections = QAction(MainWindow)
        self.actionManage_Connections.setObjectName(u"actionManage_Connections")
        self.actionTest_Ping_Connection = QAction(MainWindow)
        self.actionTest_Ping_Connection.setObjectName(u"actionTest_Ping_Connection")
        self.actionMinimize = QAction(MainWindow)
        self.actionMinimize.setObjectName(u"actionMinimize")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        self.actionNew_Test = QAction(MainWindow)
        self.actionNew_Test.setObjectName(u"actionNew_Test")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionShow_Hide = QAction(MainWindow)
        self.actionShow_Hide.setObjectName(u"actionShow_Hide")
        self.actionShow_Hide_2 = QAction(MainWindow)
        self.actionShow_Hide_2.setObjectName(u"actionShow_Hide_2")
        self.actionShow_Hide_3 = QAction(MainWindow)
        self.actionShow_Hide_3.setObjectName(u"actionShow_Hide_3")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(690, 360, 201, 191))
        self.verticalLayoutWidget = QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(50, 30, 131, 151))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.lcdNumber_3 = QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber_3.setObjectName(u"lcdNumber_3")
        self.lcdNumber_3.setLineWidth(1)

        self.verticalLayout.addWidget(self.lcdNumber_3)

        self.lcdNumber_6 = QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber_6.setObjectName(u"lcdNumber_6")

        self.verticalLayout.addWidget(self.lcdNumber_6)

        self.lcdNumber_5 = QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber_5.setObjectName(u"lcdNumber_5")

        self.verticalLayout.addWidget(self.lcdNumber_5)

        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 0, 881, 351))
        self.uploadSeqButton = QPushButton(self.groupBox)
        self.uploadSeqButton.setObjectName(u"uploadSeqButton")
        self.uploadSeqButton.setGeometry(QRect(20, 290, 201, 26))
        self.uploadSeqButton.setCheckable(False)
        self.uploadSeqButton.setChecked(False)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(530, 250, 300, 63))
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setFrameShape(QFrame.Shape.NoFrame)
        self.label_7.setPixmap(QPixmap(u"assets/swandoc_logo.png"))
        self.label_7.setScaledContents(True)
        self.gridLayoutWidget = QWidget(self.groupBox)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(510, 60, 341, 161))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)

        self.label_4 = QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)

        self.lcdNumber_8 = QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber_8.setObjectName(u"lcdNumber_8")

        self.gridLayout.addWidget(self.lcdNumber_8, 1, 1, 1, 1)

        self.lcdNumber_4 = QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber_4.setObjectName(u"lcdNumber_4")
        self.lcdNumber_4.setLineWidth(1)

        self.gridLayout.addWidget(self.lcdNumber_4, 0, 1, 1, 1)

        self.sequenceGraphFrame = QFrame(self.groupBox)
        self.sequenceGraphFrame.setObjectName(u"sequenceGraphFrame")
        self.sequenceGraphFrame.setGeometry(QRect(20, 30, 461, 261))
        self.sequenceGraphFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.sequenceGraphFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayoutWidget_2 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(230, 290, 251, 31))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setObjectName(u"label_5")
        font = QFont()
        font.setBold(True)
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_2.addWidget(self.label_5)

        self.sequenceName = QLabel(self.horizontalLayoutWidget_2)
        self.sequenceName.setObjectName(u"sequenceName")

        self.horizontalLayout_2.addWidget(self.sequenceName)

        self.selectSequenceButton = QPushButton(self.groupBox)
        self.selectSequenceButton.setObjectName(u"selectSequenceButton")
        self.selectSequenceButton.setGeometry(QRect(20, 320, 201, 26))
        self.uploadSeqButton.raise_()
        self.label_7.raise_()
        self.gridLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.sequenceGraphFrame.raise_()
        self.selectSequenceButton.raise_()
        self.footerFrame = QFrame(self.centralwidget)
        self.footerFrame.setObjectName(u"footerFrame")
        self.footerFrame.setGeometry(QRect(10, 560, 881, 31))
        self.footerFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.footerFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayoutWidget = QWidget(self.footerFrame)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(0, 0, 881, 31))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.footerTitleLabel = QLabel(self.horizontalLayoutWidget)
        self.footerTitleLabel.setObjectName(u"footerTitleLabel")

        self.horizontalLayout.addWidget(self.footerTitleLabel)

        self.footerYearLabel = QLabel(self.horizontalLayoutWidget)
        self.footerYearLabel.setObjectName(u"footerYearLabel")
        self.footerYearLabel.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.footerYearLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout.addWidget(self.footerYearLabel)

        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(9, 359, 411, 111))
        self.gridLayoutWidget_2 = QWidget(self.groupBox_3)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(10, 30, 391, 71))
        self.gridLayout_4 = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.StatusLabel = QLabel(self.gridLayoutWidget_2)
        self.StatusLabel.setObjectName(u"StatusLabel")
        self.StatusLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_4.addWidget(self.StatusLabel, 1, 1, 1, 1)

        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.label = QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName(u"label")

        self.horizontalLayout_5.addWidget(self.label)

        self.IPEdit = QLineEdit(self.gridLayoutWidget_2)
        self.IPEdit.setObjectName(u"IPEdit")

        self.horizontalLayout_5.addWidget(self.IPEdit)


        self.gridLayout_4.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)

        self.connectButton = QPushButton(self.gridLayoutWidget_2)
        self.connectButton.setObjectName(u"connectButton")

        self.gridLayout_4.addWidget(self.connectButton, 0, 1, 1, 1)

        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.label_2 = QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName(u"label_2")

        self.horizontalLayout_6.addWidget(self.label_2)

        self.portEdit = QLineEdit(self.gridLayoutWidget_2)
        self.portEdit.setObjectName(u"portEdit")

        self.horizontalLayout_6.addWidget(self.portEdit)


        self.gridLayout_4.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)

        self.ConnectionLabel = QLabel(self.gridLayoutWidget_2)
        self.ConnectionLabel.setObjectName(u"ConnectionLabel")

        self.gridLayout_4.addWidget(self.ConnectionLabel, 1, 2, 1, 1)

        self.PingButton = QPushButton(self.gridLayoutWidget_2)
        self.PingButton.setObjectName(u"PingButton")

        self.gridLayout_4.addWidget(self.PingButton, 0, 2, 1, 1)

        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 470, 411, 81))
        self.calibrateButton = QPushButton(self.groupBox_4)
        self.calibrateButton.setObjectName(u"calibrateButton")
        self.calibrateButton.setGeometry(QRect(10, 40, 131, 29))
        self.horizontalLayoutWidget_5 = QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_5.setObjectName(u"horizontalLayoutWidget_5")
        self.horizontalLayoutWidget_5.setGeometry(QRect(130, 40, 160, 31))
        self.horizontalLayout_7 = QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.label_8 = QLabel(self.horizontalLayoutWidget_5)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_7.addWidget(self.label_8)

        self.calibrationLabel = QLabel(self.horizontalLayoutWidget_5)
        self.calibrationLabel.setObjectName(u"calibrationLabel")

        self.horizontalLayout_7.addWidget(self.calibrationLabel)

        self.verticalLayoutWidget_2 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(400, 430, 314, 80))
        self.verticalLayout_6 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label_9 = QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName(u"label_9")
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(True)
        self.label_9.setFont(font1)
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_6.addWidget(self.label_9)

        self.label_10 = QLabel(self.verticalLayoutWidget_2)
        self.label_10.setObjectName(u"label_10")
        font2 = QFont()
        font2.setPointSize(9)
        self.label_10.setFont(font2)
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_6.addWidget(self.label_10)

        MainWindow.setCentralWidget(self.centralwidget)
        self.footerFrame.raise_()
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 902, 25))
        self.menuBar.setAutoFillBackground(False)
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menuBar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName(u"menuView")
        self.menuConnect = QMenu(self.menuBar)
        self.menuConnect.setObjectName(u"menuConnect")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuWindow_2 = QMenu(self.menuBar)
        self.menuWindow_2.setObjectName(u"menuWindow_2")
        MainWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuConnect.menuAction())
        self.menuBar.addAction(self.menuWindow_2.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew_Test)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_Test_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint_Window)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPreferences)
        self.menuConnect.addAction(self.actionConnect)
        self.menuConnect.addAction(self.actionDisconnect)
        self.menuConnect.addAction(self.actionManage_Connections)
        self.menuConnect.addAction(self.actionTest_Ping_Connection)
        self.menuHelp.addAction(self.actionAbout)
        self.menuWindow_2.addAction(self.actionMinimize)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open Test", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save Test", None))
        self.actionSave_Test_as.setText(QCoreApplication.translate("MainWindow", u"Save Test as", None))
        self.actionPrint_Window.setText(QCoreApplication.translate("MainWindow", u"Print Window", None))
        self.actionConnect.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.actionDisconnect.setText(QCoreApplication.translate("MainWindow", u"Disconnect", None))
        self.actionManage_Connections.setText(QCoreApplication.translate("MainWindow", u"Manage Connections", None))
        self.actionTest_Ping_Connection.setText(QCoreApplication.translate("MainWindow", u"Test / Ping Connection", None))
        self.actionMinimize.setText(QCoreApplication.translate("MainWindow", u"Minimize", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Preferences", None))
        self.actionNew_Test.setText(QCoreApplication.translate("MainWindow", u"New Test", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionShow_Hide.setText(QCoreApplication.translate("MainWindow", u"Show/Hide", None))
        self.actionShow_Hide_2.setText(QCoreApplication.translate("MainWindow", u"Show/Hide", None))
        self.actionShow_Hide_3.setText(QCoreApplication.translate("MainWindow", u"Show/Hide", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Voltage Readings", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Throttle", None))
        self.uploadSeqButton.setText(QCoreApplication.translate("MainWindow", u"Upload Throttle Sequence", None))
        self.label_7.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Programmed Throttle Position (%)", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Actual Throttle Position (%)", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Loaded Test:", None))
        self.sequenceName.setText(QCoreApplication.translate("MainWindow", u"No Sequence Loaded", None))
        self.selectSequenceButton.setText(QCoreApplication.translate("MainWindow", u"Select Throttle Sequence", None))
        self.footerTitleLabel.setText(QCoreApplication.translate("MainWindow", u"SwanSEDS | Kilgharrah Throttle Control ", None))
        self.footerYearLabel.setText(QCoreApplication.translate("MainWindow", u"2026", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Connection", None))
        self.StatusLabel.setText(QCoreApplication.translate("MainWindow", u"Status:", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"IP:", None))
        self.connectButton.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Port:", None))
        self.ConnectionLabel.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.PingButton.setText(QCoreApplication.translate("MainWindow", u"Ping", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Calibration", None))
        self.calibrateButton.setText(QCoreApplication.translate("MainWindow", u"Start Calibration", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Status:", None))
        self.calibrationLabel.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Kilgharrah Throttle Control Software", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Version 0.1.4", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuConnect.setTitle(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuWindow_2.setTitle(QCoreApplication.translate("MainWindow", u"Window", None))
    # retranslateUi

